### ISSUE TITLE
Release New Version

### ISSUE THREAD

**Issue by bentheiii** [twisted/towncrier#621] opened 2024-07-08 11:27 UTC
Hi there, can we release a new version of towncrier with all the pending additions and fixes?

**Comment by adiroiban** [comment] 2024-07-08 18:55
This looks like a duplicate of #616

**Closed as not planned by adiroiban** 2024-07-08 18:55 UTC

**Comment by adiroiban** [comment] 2024-07-08 18:57
Please follw up with with the discussion over #616 

Happy to have a new release, as long as there is someone willing to test and use it :)
