### ISSUE TITLE
orphan fragments that contain a number in the filename are linked to issues.

### ISSUE THREAD

**Issue by mdellweg** [twisted/towncrier#562] opened 2023-11-06 09:25 UTC
e.g. calling the fragment `CHANGES/+compat.somelib_1.12.feature` will link the supposed orphan snippet to the issue `#12`.

**Comment by adiroiban** [comment] 2023-11-06 13:40
Thanks for the report

It looks like we have some missing automated tests.

I think that the fix can start by writing an automated test (or updating the current one) for this filename and see the test failing.

I think that the issue is somewhere here:

https://github.com/twisted/towncrier/blob/a794718b345cb332cd16ce9a807f4c02c68088d3/src/towncrier/_builder.py#L107-L119

or here 

https://github.com/twisted/towncrier/blob/a794718b345cb332cd16ce9a807f4c02c68088d3/src/towncrier/_builder.py#L27-L61

I would be happy to review a fix for this :)

**Comment by mdellweg** [comment] 2023-11-07 08:51
I started adding to a test: https://github.com/twisted/towncrier/pull/564
Do you want to see it red before fixing it?

Also your two code snippets are the same. Did you mention to point me to another area too?

**Comment by adiroiban** [comment] 2023-11-07 09:01
Awesome. I have enabled the tests on that PR.

I have updated the code link

**Closed as completed** 2023-11-07 15:54 UTC
