### ISSUE TITLE
Towncrier reports a wrong version of itself

### ISSUE THREAD

**Issue by gforcada** [twisted/towncrier#533] opened 2023-07-12 09:53 UTC
I was getting confused:

```shell
$ towncrier --version
towncrier, version 22.12.0
```

But:

```shell
$ pip list | grep towncrier
towncrier             23.6.0
```

Is that expected?

**Comment by hynek** [comment] 2023-07-12 10:06
Try running `type towncrier` to ensure you're not running a global towncrier.

**Comment by adiroiban** [comment] 2023-07-12 10:08
thanks for the report.
it works for me.

I am closing this.

If this is still a problem, please send the steps to reproduce this

```
11:06 $ cd ~/tmp/
adi@g14:~/tmp$ virtualenv town3
created virtual environment CPython3.10.6.final.0-64 in 196ms
  creator CPython3Posix(dest=/home/adi/tmp/town3, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/adi/Dropbox/.local/share/virtualenv)
    added seed packages: pip==23.1.2, setuptools==67.8.0, wheel==0.40.0
  activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
adi@g14:~/tmp$ cd town3/
adi@g14:~/tmp/town3$ . bin/activate
(town3) adi@g14:~/tmp/town3$ pip install towncrier
Collecting towncrier
  Downloading towncrier-23.6.0-py3-none-any.whl (46 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 46.3/46.3 kB 805.4 kB/s eta 0:00:00
Collecting click (from towncrier)
  Downloading click-8.1.4-py3-none-any.whl (98 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 98.2/98.2 kB 2.3 MB/s eta 0:00:00
Collecting click-default-group (from towncrier)
  Using cached click_default_group-1.2.2-py3-none-any.whl
Collecting incremental (from towncrier)
  Using cached incremental-22.10.0-py2.py3-none-any.whl (16 kB)
Collecting jinja2 (from towncrier)
  Using cached Jinja2-3.1.2-py3-none-any.whl (133 kB)
Collecting tomli (from towncrier)
  Using cached tomli-2.0.1-py3-none-any.whl (12 kB)
Collecting MarkupSafe>=2.0 (from jinja2->towncrier)
  Using cached MarkupSafe-2.1.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (25 kB)
Installing collected packages: incremental, tomli, MarkupSafe, click, jinja2, click-default-group, towncrier
Successfully installed MarkupSafe-2.1.3 click-8.1.4 click-default-group-1.2.2 incremental-22.10.0 jinja2-3.1.2 tomli-2.0.1 towncrier-23.6.0
(town3) adi@g14:~/tmp/town3$ towncrier --version
towncrier, version 23.6.0
(town3) adi@g14:~/tmp/town3$ 
```

**Closed as not planned by adiroiban** 2023-07-12 10:08 UTC
