### ISSUE TITLE
title_format = false has no effect

### ISSUE THREAD

**Issue by vytas7** [twisted/towncrier#345] opened 2021-04-25 11:09 UTC
This is somewhat similar to another issue I reported about `title_format = false` causing an error (https://github.com/twisted/towncrier/issues/164); now it is accepted but at least in some scenarios it seems to have no effect.

Moreover, unless I'm misunderstanding how this works, it looks like the added test (verifying the `title_format = false` behaviour) uses an incorrect assertion, illustrating the title is erroneously rendered regardless of the setting: https://github.com/twisted/towncrier/blob/master/src/towncrier/test/test_build.py#L770:
```python
        expected_output = dedent("""\
            Loading template...
            Finding news fragments...
            Rendering news fragments...
            Draft only -- nothing has been written.
            What is seen below is what would be written.
            FooBarBaz 7.8.9 (20-01-2001)
            ============================
            Features
            --------
            - Extends levitation (#124)
        """)
```

I happened to miss this when I said on https://github.com/twisted/towncrier/issues/164 this was fixed for me; I was checking that the option now longer raised an exception, but missed the incorrect behaviour: https://github.com/twisted/towncrier/pull/299/files#r619798640.

**Comment by DudeNr33** [comment] 2022-06-16 09:09
I came across the same problem. 
Until this is fixed, I use the following workaround:

```toml
[tool.towncrier]
underlines = [
    "",   # For title - we don't need one, so we leave this as empty string
    "=",  # For categories
    "-",  # For ???
]
title_format = ".. nocontent"  # hack to hide the title generated by towncrier
```

**Comment by adiroiban** [comment] 2022-06-16 09:53
In master test I see that the title is no longer there

**Comment by adiroiban** [comment] 2022-06-16 18:03
thanks for the info.

the code is here ...and it has some backward incompatible stuff

https://github.com/twisted/towncrier/blob/21c11748e9c21c270b221af28d07baf93fdb1980/src/towncrier/build.py#L142-L171

The configuration name is `title_format`.

Where have you found the `title = false` example?

Can you try this change?

```diff
[tool.towncrier]
version = "1.0"
-title = false
+title_format = false

```

**Comment by DudeNr33** [comment] 2022-06-16 18:35
Oops, my bad. It should have been `title_format` of course.
When applying your suggested change, the current code from `master` works as expected.
The latest release on PyPI still generates the title.

So this will be fixed in the next release - good to know!

**Comment by adiroiban** [comment] 2022-06-16 18:51
Ok. So I am going to close this, as the issue is fixed...but not released.

Now. I guess that we should do a new release.

Let me know if you would like to have a new release and have time to test the release candidate.

I am mostly doing maintenance work for this project. 
I am using towncrier for more than 5 years and it works fine with a custom template so I don't really need a new release.

But if you have time to test a new release, we can go with it.

**Closed by adiroiban** 2022-06-16 18:51 UTC

**Comment by DudeNr33** [comment] 2022-06-18 08:30
Hi @adiroiban, thanks for your offer to make a new release.
I am just starting to use `towncrier`, so I do not have a reference point what worked in the past and should still work with the new RC. 
I will continue my integration of `towncrier` with the currently released version, and then check if everything still works when installing the current version from `master`. 
Then I can give feedback how those tests went. 😊
