### ISSUE TITLE
Chicken-and-egg problem with `--check` option

### ISSUE THREAD

**Issue by freakboy3742** [twisted/towncrier#246] opened 2020-05-16 03:42 UTC
If you add `towncrier --check` as a CI check, it is possible to verify that every PR that is merged has a matching release note. This is useful for ensuring final release notes are complete.

However, when you cut a release, a user will submit a PR that incorporates the final compiled release notes, along with a version number bump and any other release procedures. 

This "release PR" then fails the towncrier CI check, as it doesn't have a news snippet. 

You can make the PR pass CI by adding a 'misc' release note for  the release PR. However this means the release notes for the next version include an entry about cutting the *previous* release. 

There should be a way to avoid this "chicken and egg" problem without irrelevant dummy entries in changelog history.

**Comment by freakboy3742** [comment] 2020-05-16 03:42
I can think of two possible fixes; there may be others:

1) Adding a `ignore` release note type that can be used for procedural release notes. This provides a placeholder that can satisfy the check, but doesn't dirty the release notes for the next release with irrelevant details. This could also be used for PRs that aren't tied to a ticket, and are entirely procedural (e.g., a PR that is needed to test/fix CI/CD infrastructure).
2) Modifying `towncrier --check` so that a diff containing an empty snippets directory *and* an update to the target release file passes.

**Comment by vcalvert** [comment] 2020-10-21 17:10
Duplicate of #152; there's a PR in #174.

**Comment by adiroiban** [comment] 2020-12-20 15:56
My suggestion from the PR. Add a `--check-release` that will do special towncrier checks required for a release:
* fail if the branch has any news fragments

It would be nice to have all this behavior in `--check` but how can you tell which branch/PR is a release and which not.

You can modify your CI system to detect a release branch and then call `--check-release` instead of `--check`.

For my process, the release branch is also updating the version file and not only the release notes files.
So we need a way to detect a release branch.

But meanwhile, while we discuss how to detect a release branch in a way that will work for anyone, I think that we can add `--check-release` and at least have the logic for the release checks.

**Closed** 2022-02-13 22:07 UTC
Labels: bug

**Comment by kasium** [comment] 2022-08-23 09:03
@adiroiban any plans to release this in the next time?
